### ISSUE TITLE
No dbus connection to host ?

### ISSUE THREAD

**Issue by decodeais** [iuriaranda/venus-docker#2]
For me everything seams to be OK. But it seems to me that there is no dbus connection to the host. If I want to use  the victron nodes on nodered they find no device. What must be done to establish the connection to host.
```
 ⠿ Container venus-docker-main-localsettings-1       Created                                                                                       0.0s
 ⠿ Container venus-docker-main-dbus-1                Created                                                                                       0.0s
 ⠿ Container venus-docker-main-dbus-systemcalc-py-1  Created                                                                                       0.0s
 ⠿ Container venus-docker-main-vedirect-1            Created                                                                                       0.0s
Attaching to venus-docker-main-dbus-1, venus-docker-main-dbus-systemcalc-py-1, venus-docker-main-localsettings-1, venus-docker-main-vedirect-1
venus-docker-main-localsettings-1       | localsettings v1.52 starting up 
venus-docker-main-localsettings-1       | INFO:root:Localsettings version is: 0x0152
venus-docker-main-localsettings-1       | INFO:root:Settings file /data/conf/settings.xml validated
venus-docker-main-vedirect-1            | vedirect-dbus 3.70
venus-docker-main-dbus-systemcalc-py-1  | -------- dbus_systemcalc, v2.103 is starting up --------
venus-docker-main-dbus-systemcalc-py-1  | INFO:logger:Loglevel set to INFO
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbusmonitor:===== Search on dbus for services that we will monitor starting... =====
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbusmonitor:Found: com.victronenergy.settings, scanning and storing items
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbusmonitor:       com.victronenergy.settings has device instance 0
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbusmonitor:===== Search on dbus for services that we will monitor finished =====
venus-docker-main-dbus-systemcalc-py-1  | INFO:vedbus:registered ourselves on D-Bus as com.victronenergy.system
venus-docker-main-dbus-systemcalc-py-1  | INFO:relaystate:No relays found
venus-docker-main-dbus-systemcalc-py-1  | INFO:buzzercontrol:No buzzer found
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbus_systemcalc:Battery service initialized to None (setting == default)
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbus_systemcalc:Starting mainloop, responding only on events
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbusmonitor:Found: com.victronenergy.solarcharger.instance0, scanning and storing items
venus-docker-main-dbus-systemcalc-py-1  | INFO:dbusmonitor:       com.victronenergy.solarcharger.instance0 has device instance 0

```

**Comment by iuriaranda** [comment]
Interesting question. For context, the main purpose of the dbus container is to run an isolated D-Bus for just the Venus services, separated from the host system D-Bus.

I think there are different ways you can do this:

1. You can run all Venus services on the host system D-Bus and not run the dbus container. For that you'd need to replace the `"var_run_dbus:/var/run/dbus"` volume in all the containers to `"/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"`. But then in this case you'll also need to modify your system D-Bus config (normally located in `/etc/dbus-1/system.d`) to allow `com.victronenergy.*` topics to be sent. Not sure of what exactly you need there, but you can use the [config file in the dbus image](https://github.com/iuriaranda/venus-docker/blob/6b7f0a5ea60a917c541c3516302d075b9514a3a5/dbus/victron.conf) as a reference.
2. You can point Node red to use the D-Bus socket of the dbus container. You can find out the path in your host system for the `var_run_dbus` volume mounted inside the container, and use that path to set the `DBUS_SYSTEM_BUS_ADDRESS` environment variable for Node Red. e.g `DBUS_SYSTEM_BUS_ADDRESS=/var/lib/docker/volumes/var_run_dbus/_data/system_bus_socket`. You can find out where a specific volume is mounted by running `docker volume inspect VOLUMENAME`.
3. You can also expose the Venus D-Bus over TCP and expose it in a host port. I'd argue this is the least desirable option, since it would expose the Venus D-Bus to the whole network where the host system is connected to.

I guess that the easiest, if you can make the proper changes to the host system D-Bus configuration, is to use the first option. This way the Node Red Victron plugin will work out of the box.

**Comment by iuriaranda** [comment]
A little update on option nr. 1, you'll need to allow the venus services to use the bus. You can do this by running the following command:

```bash
sudo tee -a /etc/dbus-1/system.d/com.victronenergy.conf > /dev/null << EOF
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN" "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<busconfig>
        <policy user="root">
                <allow own_prefix="com.victronenergy"/>
                <allow send_destination="*"/>
        </policy>
</busconfig>
EOF
```

This will create a new file in `/etc/dbus-1/system.d/com.victronenergy.conf` with the necessary configuration. Note that if you're running on Ubuntu, you'll also need to run the docker containers as privileged because of some AppArmor policies, at least that was the case in my tests. Apparently that's not necessary in Debian or raspbian.

I'll probably add this option of running on the host system DBus as an example in the documentation. For now I think we can close this issue.
